### ISSUE TITLE
Menu Icon Issues

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/themeisle-companion#121]
### When you have a lot of menu items, the menus dashboard page freezes the browser.
This is probably because of the multiple iconpickers and because they parse the icons array dinamically. 

### When adding a new element to the menu, there are two add icon buttons.

![image](https://user-images.githubusercontent.com/15010186/33017739-23a4c352-cdfc-11e7-8e26-11e7d809b1b4.png)

The two buttons appear on the top menu item.

### When the menu contains invalid menu items (pages / posts that have been deleted), sometimes it throws a js error.

```
Uncaught TypeError: Cannot read property 'match' of undefined
    at get_prefix (admin.js:18)
    at add_icon (admin.js:51)
    at HTMLLIElement.<anonymous> (admin.js:34)
    at Function.each (load-scripts.php:2)
    at a.fn.init.each (load-scripts.php:2)
    at admin.js:31
    at Array.forEach (<anonymous>)
    at MutationObserver.<anonymous> (admin.js:30)
```

**Comment by contactashish13** [comment]
@abaicus 

> When you have a lot of menu items, the menus dashboard page freezes the browser.

does this freeze on page load or when you try to select an icon?

> When adding a new element to the menu, there are two add icon buttons.

when adding a new element, its usually added at the bottom but in the issue it seems like its being added at the top. I cannot seem to reproduce the issue; maybe it is a specific scenario?

**Comment by abaicus** [comment]
@contactashish13 
1. It freezes on page load, can't do anything else. 
2. It seems to only happen from time to time, not always. I can't really reproduce it either at the moment.

**Comment by contactashish13** [comment]
@abaicus 

> When the menu contains invalid menu items (pages / posts that have been deleted), sometimes it throws a js error.

can you please list down the steps to reproduce this? for me, this is what it shows after I delete a post that was added to the menu (and no JS error):

![image](https://user-images.githubusercontent.com/12953439/33310191-cd3009fe-d446-11e7-9f94-4053c88213b7.png)

**Comment by abaicus** [comment]
Try adding a lot of menu items in the menu - also submenus. I'm talking about a lot more menu items. 

Can't get the second js error to come up either. I don't know why.

**Comment by selul** [comment]
@contactashish13 please have a look at that HS ticket that andrei assigned to you.

**Comment by contactashish13** [comment]
@selul @abaicus https://github.com/Codeinwp/themeisle-companion/pull/134 should fix these issues. Can you please test locally in case I've forgotten to test a scenario and then I can apply this on the customer's instance?

**Comment by selul** [comment]
@abaicus did you manage to test it ?

**Comment by abaicus** [comment]
@contactashish13  This happens when you drag and drop any menu item on my instance. Another plus appears. 

![image](https://user-images.githubusercontent.com/15010186/33543321-3aebcb30-d8df-11e7-9871-333a34ea0184.png)

**Comment by contactashish13** [comment]
@abaicus have addressed this. can you please test again?

**Comment by abaicus** [comment]
![image](https://user-images.githubusercontent.com/15010186/33546536-f1224b36-d8e9-11e7-8998-ad0e2cdd85d4.png)
Still getting this when trying to move anything. Loading seems to be improved though. 👍 @contactashish13

**Comment by contactashish13** [comment]
@abaicus can you try to clear your cache and test as most of these changes are in the JS file?

**Comment by abaicus** [comment]
My cache is cleared. Also happens under Safari and Firefox, which are browsers from where I've never accessed this.

![image](https://user-images.githubusercontent.com/15010186/33546767-93ac8b46-d8ea-11e7-9e26-85892ac9d9de.png)
![image](https://user-images.githubusercontent.com/15010186/33546785-9c6237ae-d8ea-11e7-81c2-c611eb23b4e1.png)

**Comment by contactashish13** [comment]
@abaicus I didn't notice the error before. I've addressed it now.

**Comment by abaicus** [comment]
Seems to be working fine now! 👍
